// Public-consumer Aspire TypeScript AppHost: runs the PUBLIC Sekiban WASM
// runtime container image and a Postgres event DB, exactly as an external
// TypeScript-first developer would. The container wiring comes from the
// @sekiban/aspire helper (referenced as a local package until the first npm
// publish; an external consumer installs it from npm).
//
// The wasm module + manifest are the ones generated by the CsDecider
// public-container sample (the hosting model is language-agnostic — the same
// module runs regardless of which AppHost language starts the container):
//   bash src/samples/Sekiban.Dcb.WasmRuntime.PublicContainer.CsDecider/scripts/build-wasm.sh

import { existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createBuilder } from "./.aspire/modules/aspire.mjs";
import { addSekibanWasmRuntime } from "@sekiban/aspire";

const sampleDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(sampleDir, "..", "..", "..");
const artifactDir = join(repoRoot, "artifacts", "samples", "public-container-cs-decider");
const modulesDir = join(artifactDir, "modules");
const configDir = join(artifactDir, "config");
const moduleFileName = "public-container-cs-decider.wasm";

// Fail closed with a clear repair command if the mounted inputs are missing.
if (!existsSync(join(modulesDir, moduleFileName)) || !existsSync(join(configDir, "sekiban-manifest.json"))) {
  console.error(
    `[apphost] Missing WASM module or manifest under ${artifactDir}.\n` +
      "[apphost] Build them first:\n" +
      "  bash src/samples/Sekiban.Dcb.WasmRuntime.PublicContainer.CsDecider/scripts/build-wasm.sh",
  );
  process.exit(1);
}

const builder = await createBuilder();

// Naming the databases "SekibanDcb" and "DcbMaterializedViewPostgres" makes the
// references inject exactly the connection-string keys the runtime expects.
const postgres = builder.addPostgres("pg");
const sekibanDb = postgres.addDatabase("SekibanDcb");
const materializedViewDb = postgres.addDatabase("DcbMaterializedViewPostgres");

// The smoke script pins a known host port via SAMPLE_RUNTIME_HOST_PORT so it can
// reach the runtime deterministically; otherwise Aspire assigns one. The image
// tag honors SAMPLE_RUNTIME_IMAGE_TAG (default 1.0.0-preview.3) inside the helper.
const hostPortEnv = Number.parseInt(process.env.SAMPLE_RUNTIME_HOST_PORT ?? "", 10);

await addSekibanWasmRuntime(builder, "runtime", {
  configDirectory: configDir,
  modulesDirectory: modulesDir,
  wasmModulePath: `/app/modules/${moduleFileName}`,
  references: [sekibanDb, materializedViewDb],
  ...(Number.isFinite(hostPortEnv) && hostPortEnv > 0 ? { hostPort: hostPortEnv } : {}),
});

await builder.build().run();
