#!/usr/bin/env bash
set -uo pipefail

cd "$(git rev-parse --show-toplevel)"

package_version="${PACKAGE_VERSION:-${1:-1.0.0-preview.dryrun.0}}"
package_version="${package_version#v}"

if [[ ! "$package_version" =~ ^1\.0\.0-preview\.[0-9A-Za-z.-]+$ ]]; then
  printf 'Package version must be 1.0.0-preview.*; got %s\n' "$package_version" >&2
  exit 1
fi

artifact_root="${RELEASE_DRY_RUN_ARTIFACT_ROOT:-artifacts/preview-release-dry-run}"
nuget_dir="$artifact_root/nuget"
artifact_report_dir="$artifact_root/release"
report_path="${RELEASE_DRY_RUN_REPORT:-reports/public-release/preview-release-dry-run.md}"
tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

rm -rf "$artifact_root"
mkdir -p "$nuget_dir" "$artifact_report_dir" "$(dirname "$report_path")"

fail_count=0
warn_count=0
step_rows=()

write_header() {
  {
    printf '# Preview Release Readiness Dry Run\n\n'
    printf 'Issue: `#131` / `SWR-G009 Release readiness dry-run evidence pack`\n\n'
    printf '## Scope\n\n'
    printf 'This report is generated by `%s` and records the CI-safe readiness path for preview packages.\n' "$0"
    printf 'It does not create a GitHub Release, does not push NuGet packages, and does not require a real NuGet credential.\n\n'
    printf '%s\n' "- Package version: \`$package_version\`"
    printf '%s\n' "- Commit: \`$(git rev-parse HEAD)\`"
    printf '%s\n' "- NuGet output: \`$nuget_dir\`"
    printf '%s\n\n' "- Release report output: \`$artifact_report_dir\`"
    printf '## Publish Safety\n\n'
    printf '| Guard | Status | Evidence |\n'
    printf '| --- | --- | --- |\n'
    printf '| GitHub Release creation | PASS | Not attempted by this script. |\n'
    printf '| NuGet publish | PASS | `dotnet nuget push` is not invoked by this script. |\n'
  } > "$report_path"

  if [[ -n "${NUGET_API_KEY:-}" ]]; then
    printf '| NuGet credential | PASS | `NUGET_API_KEY` is present, but dry-run mode does not use it. |\n' >> "$report_path"
  else
    printf '| NuGet credential | WARN | `NUGET_API_KEY` is missing; this is safe for dry-run and would block real publish. |\n' >> "$report_path"
    warn_count=$((warn_count + 1))
  fi

  printf '\n## Check Details\n\n' >> "$report_path"
}

append_output_block() {
  local output_file="$1"
  if [[ -s "$output_file" ]]; then
    sed -e 's/\r$//' "$output_file" | awk '{ if ($0 == "") print ""; else print "    " $0 }' >> "$report_path"
    printf '\n' >> "$report_path"
  else
    printf '_No output._\n\n' >> "$report_path"
  fi
}

record_step() {
  local name="$1"
  local status="$2"
  local command="$3"
  local detail="$4"
  local output_file="$5"

  step_rows+=("| $name | $status | \`$command\` | $detail |")

  {
    printf '### %s\n\n' "$name"
    printf '%s\n' "- Status: \`$status\`"
    printf '%s\n' "- Command: \`$command\`"
    printf '%s\n\n' "- Outcome: $detail"
  } >> "$report_path"
  append_output_block "$output_file"

  case "$status" in
    FAIL) fail_count=$((fail_count + 1)) ;;
    WARN) warn_count=$((warn_count + 1)) ;;
  esac
}

run_step() {
  local name="$1"
  local detail_pass="$2"
  shift 2
  local command_text="$*"
  local output_file="$tmp_dir/${name//[^A-Za-z0-9]/_}.log"

  printf 'running: %s\n' "$command_text"
  bash -lc "$command_text" > "$output_file" 2>&1
  local status=$?
  if (( status == 0 )); then
    record_step "$name" PASS "$command_text" "$detail_pass" "$output_file"
  else
    record_step "$name" FAIL "$command_text" "Exited with status $status; follow up before release." "$output_file"
  fi
}

write_summary() {
  local summary_file="$tmp_dir/summary.md"
  {
    printf '## Summary\n\n'
    printf '| Check | Status | Command | Outcome |\n'
    printf '| --- | --- | --- | --- |\n'
    for row in "${step_rows[@]}"; do
      printf '%s\n' "$row"
    done
    printf '| Missing NuGet credential behavior | WARN | `NUGET_API_KEY` environment check | Missing credentials are safe in dry-run; real publish remains blocked. |\n'
    printf '\n## Result\n\n'
    if (( fail_count > 0 )); then
      printf 'FAIL: `%s` readiness check(s) failed; fix blockers before publishing.\n' "$fail_count"
    elif (( warn_count > 0 )); then
      printf 'PASS with WARN: readiness checks passed and `%s` warning(s) were recorded for dry-run-only conditions.\n' "$warn_count"
    else
      printf 'PASS: readiness checks passed without warnings.\n'
    fi
  } > "$summary_file"

  python3 - "$summary_file" "$report_path" <<'PY'
import sys
from pathlib import Path

summary = Path(sys.argv[1]).read_text(encoding="utf-8")
report = Path(sys.argv[2])
body = report.read_text(encoding="utf-8")
marker = "## Check Details\n\n"
report.write_text(body.replace(marker, summary + "\n" + marker), encoding="utf-8")
PY
}

normalize_report() {
  python3 - "$report_path" <<'PY'
import sys
from pathlib import Path

report = Path(sys.argv[1])
lines = [line.rstrip() for line in report.read_text(encoding="utf-8").splitlines()]
while lines and lines[-1] == "":
    lines.pop()
report.write_text("\n".join(lines) + "\n", encoding="utf-8")
PY
}

write_header

run_step \
  "Pack and package inspection" \
  "Packed and inspected the three public package candidates with preview metadata." \
  "PACKAGE_VERSION='$package_version' NUGET_OUTPUT_DIR='$nuget_dir' RELEASE_REPORT_DIR='$artifact_report_dir' scripts/release/inspect-nuget-packages.sh '$package_version'"

run_step \
  "Secret scan" \
  "High-confidence secret patterns were not found in tracked repository content." \
  "scripts/release/check-secrets.sh"

run_step \
  "License and notice" \
  "Required license, notice, package README, and release evidence files were present." \
  "scripts/release/check-license-notice.sh"

run_step \
  "Public hygiene" \
  "Public repository hygiene guardrails passed." \
  "scripts/check-public-hygiene.sh"

run_step \
  "Artifact inventory" \
  "Release artifact inventory was generated with package hashes and tracked release assets." \
  "NUGET_OUTPUT_DIR='$nuget_dir' RELEASE_REPORT_DIR='$artifact_report_dir' scripts/release/write-artifact-inventory.sh"

run_step \
  "Compatibility evidence" \
  "Runtime-owned serialized DCB contract black-box baseline passed." \
  "scripts/contract/run-serialized-dcb-contract-baseline.sh"

normalize_report

run_step \
  "Whitespace" \
  "Git whitespace validation passed." \
  "git diff --check"

write_summary
normalize_report
cat "$report_path"

if (( fail_count > 0 )); then
  exit 1
fi
