import fs from "node:fs/promises";
import path from "node:path";
import type { LanguageId, LanguageInfo, Mode } from "./languages.js";
import { templateDir } from "./languages.js";

async function copyDir(src: string, dest: string): Promise<void> {
  await fs.mkdir(dest, { recursive: true });
  const entries = await fs.readdir(src, { withFileTypes: true });
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      await copyDir(srcPath, destPath);
    } else {
      await fs.copyFile(srcPath, destPath);
    }
  }
}

function modeBanner(mode: Mode, info: LanguageInfo): string {
  const modeInfo = mode === "registry" ? info.registry : info.dev;
  const lines = [
    "<!-- generated by create-sekiban-wasm -->",
    `# Generated by \`create-sekiban-wasm\` (mode: \`${mode}\`)`,
    "",
    modeInfo.note ? modeInfo.note : "",
    "",
    "---",
    "",
  ].filter((line, index, all) => !(line === "" && all[index - 1] === ""));
  return lines.join("\n");
}

export async function generateProject(
  language: LanguageId,
  mode: Mode,
  info: LanguageInfo,
  targetDir: string,
): Promise<void> {
  const srcDir = templateDir(language, mode);
  await copyDir(srcDir, targetDir);

  const readmePath = path.join(targetDir, "README.md");
  try {
    const existing = await fs.readFile(readmePath, "utf8");
    await fs.writeFile(readmePath, `${modeBanner(mode, info)}\n${existing}`);
  } catch {
    // No README.md in the template (unexpected, but not fatal to generation).
  }

  // Shell scripts must stay executable after being copied out of the tarball.
  await chmodShellScripts(targetDir);
}

async function chmodShellScripts(dir: string): Promise<void> {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const entryPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      await chmodShellScripts(entryPath);
    } else if (entry.name.endsWith(".sh")) {
      await fs.chmod(entryPath, 0o755);
    }
  }
}
