#!/usr/bin/env bash
set -uo pipefail

cd "$(git rev-parse --show-toplevel)"

repo_root="$(pwd)"
test_project="src/internalUsages/cs/SekibanWasm.Cs.Tests/SekibanWasm.Cs.Tests.csproj"
report_path="${CONTRACT_BASELINE_REPORT:-reports/compatibility/serialized-dcb-contract-black-box-baseline.md}"
tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

mkdir -p "$(dirname "$report_path")"

test_filter='FullyQualifiedName~HttpSerializedDcbClientTests|FullyQualifiedName~InProcSerializedDcbClientTests|FullyQualifiedName~SerializedCommandEndpointContractTests|FullyQualifiedName~SerializedCommandEndpointsExecuteTests|FullyQualifiedName~RemoteSekibanExecutorTests|FullyQualifiedName~WeatherQueryClientTests|FullyQualifiedName~HttpSerializedQueryClientTests|FullyQualifiedName~WasmTagStatePrimitiveTests'
test_command="dotnet test $test_project -c Release --no-restore --filter '$test_filter'"
output_file="$tmp_dir/contract-baseline.log"

sanitize_output() {
  sed -e 's/\r$//' -e "s#${repo_root}#<repo>#g"
}

printf 'running: %s\n' "$test_command"
bash -lc "$test_command" > "$output_file" 2>&1
status=$?

if (( status == 0 )); then
  result="PASS"
  outcome="Runtime-owned serialized DCB command, query, tag state, and compatibility scenarios passed."
else
  result="FAIL"
  outcome="Exited with status $status; fix runtime contract regressions before release readiness can pass."
fi

{
  printf '# Serialized DCB Contract Black-Box Baseline\n\n'
  printf 'Issue: `#133` / `SWR-G010 Contract black-box e2e executable baseline`\n\n'
  printf '## Result\n\n'
  printf '%s: %s\n\n' "$result" "$outcome"
  printf '## Scope\n\n'
  printf 'This report is generated by `%s` and records the CI-safe runtime-owned black-box baseline for the public serialized DCB contract.\n\n' "$0"
  printf 'The baseline uses only the public runtime client and endpoint surfaces in this repository. It does not use real hosted-provider credentials, private provider configuration, or downstream service-specific client helpers.\n\n'
  printf '%s\n' "- Test project: \`$test_project\`"
  printf '%s\n' "- Commit: \`$(git rev-parse HEAD)\`"
  printf '%s\n\n' "- Command: \`$test_command\`"
  printf '## Responsibility Boundary\n\n'
  printf '| Area | Runtime baseline in this repository | Downstream provider responsibility |\n'
  printf '| --- | --- | --- |\n'
  printf '| Command commit | Serialized HTTP, in-process, endpoint contract, endpoint execute, and remote executor tests. | Execute the same serialized command path through the real hosted provider. |\n'
  printf '| Query | Serialized query client, remote executor, and weather query client tests. | Run scalar and list queries through the real hosted client and authorization flow. |\n'
  printf '| Tag state | Serialized DCB client, in-process DCB client, and WASM tag-state primitive tests. | Read tag state through the real hosted provider and credential path. |\n'
  printf '| Compatibility | Public serialized DTO, endpoint, executor, C# sample, and Rust/WASM tag-state surfaces. | Confirm hosted provider accepts the same serialized DTO and endpoint semantics. |\n\n'
  printf '## Evidence Matrix\n\n'
  printf '| Requirement | Executable evidence |\n'
  printf '| --- | --- |\n'
  printf '| Command commit | `HttpSerializedDcbClientTests`, `InProcSerializedDcbClientTests`, `SerializedCommandEndpointContractTests`, `SerializedCommandEndpointsExecuteTests`, `RemoteSekibanExecutorTests`. |\n'
  printf '| Query | `HttpSerializedQueryClientTests`, `RemoteSekibanExecutorTests`, `WeatherQueryClientTests`. |\n'
  printf '| Tag state | `HttpSerializedDcbClientTests`, `InProcSerializedDcbClientTests`, `WasmTagStatePrimitiveTests`. |\n'
  printf '| Runtime compatibility | `SerializedCommandEndpointContractTests`, `SerializedCommandEndpointsExecuteTests`, `RemoteSekibanExecutorTests`, `WasmTagStatePrimitiveTests`. |\n\n'
  printf '## Output\n\n'
  if [[ -s "$output_file" ]]; then
    sanitize_output < "$output_file" | awk '{ if ($0 == "") print ""; else print "    " $0 }'
  else
    printf '_No output._\n'
  fi
} > "$report_path"

cat "$report_path"

exit "$status"
